const machines = {
  0x14c: 'Intel 386',
  0x8664: 'x64',
  0x162: 'MIPS R3000',
  0x168: 'MIPS R10000',
  0x169: 'MIPS little endian WCI v2',
  0x183: 'old Alpha AXP',
  0x184: 'Alpha AXP',
  0x1a2: 'Hitachi SH3',
  0x1a3: 'Hitachi SH3 DSP',
  0x1a6: 'Hitachi SH4',
  0x1a8: 'Hitachi SH5',
  0x1c0: 'ARM little endian',
  0x1c2: 'Thumb',
  0x1c4: 'ARMv7',
  0x1d3: 'Matsushita AM33',
  0x1f0: 'PowerPC little endian',
  0x1f1: 'PowerPC with floating point support',
  0x200: 'Intel IA64',
  0x266: 'MIPS16',
  0x268: 'Motorola 68000 series',
  0x284: 'Alpha AXP 64-bit',
  0x366: 'MIPS with FPU',
  0x466: 'MIPS16 with FPU',
  0xebc: 'EFI Byte Code',
  0x9041: 'Mitsubishi M32R little endian',
  0xaa64: 'ARM64 little endian',
  0xc0ee: 'clr pure MSIL'
};

function determineMachine(code) {
  if (machines[code]) return machines[code] + ' (' + code.toString(16).toUpperCase() + s16 + ')';
  return 'unknown code (' + code + ')';
}

const chrs = {
  0x0001: ['RELOCS_STRIPPED', 'Relocation information was stripped from file'],
  0x0002: ['EXECUTABLE_IMAGE', 'The file is executable'],
  0x0004: ['LINE_NUMS_STRIPPED', 'COFF line numbers were stripped from file'],
  0x0008: ['LOCAL_SYMS_STRIPPED', 'COFF symbol table entries were stripped from file'],
  0x0010: ['AGGRESIVE_WS_TRIM', 'Aggressively trim the working set(obsolete)'],
  0x0020: ['LARGE_ADDRESS_AWARE', 'The application can handle addresses greater than 2 GB'],
  0x0080: ['BYTES_REVERSED_LO', 'The bytes of the word are reversed(obsolete)'],
  0x0100: ['32BIT_MACHINE', 'The computer supports 32-bit words'],
  0x0200: ['DEBUG_STRIPPED', 'Debugging information was removed and stored separately in another file'],
  0x0400: ['REMOVABLE_RUN_FROM_SWAP', 'If the image is on removable media, copy it to and run it from the swap file'],
  0x0800: ['NET_RUN_FROM_SWAP', 'If the image is on the network, copy it to and run it from the swap file'],
  0x1000: ['SYSTEM', 'The image is a system file'],
  0x2000: ['DLL', 'The image is a DLL file'],
  0x4000: ['UP_SYSTEM_ONLY', 'The image should only be ran on a single processor computer'],
  0x8000: ['BYTES_REVERSED_HI', 'The bytes of the word are reversed(obsolete)']
};

const subsystems = {
  0: ['UNKNOWN', 'Unknown subsystem.'],
  1: ['NATIVE', 'No subsystem required (device drivers and native system processes).'],
  2: ['WINDOWS_GUI', 'Windows graphical user interface (GUI) subsystem.'],
  3: ['WINDOWS_CUI', 'Windows character-mode user interface (CUI) subsystem.'],
  5: ['OS2_CUI', 'OS/2 CUI subsystem.'],
  7: ['POSIX_CUI', 'POSIX CUI subsystem.'],
  9: ['WINDOWS_CE_GUI', 'Windows CE system.'],
  10: ['EFI_APPLICATION', 'Extensible Firmware Interface (EFI) application.'],
  11: ['EFI_BOOT_SERVICE_DRIVER', 'EFI driver with boot services.'],
  12: ['EFI_RUNTIME_DRIVER', 'EFI driver with run-time services.'],
  13: ['EFI_ROM', 'EFI ROM image.'],
  14: ['XBOX', 'Xbox system.'],
  16: ['WINDOWS_BOOT_APPLICATION', 'Boot application.']
};

const dllCharacteristics = {
  0x0001: ['Reserved.', 'Reserved'],
  0x0002: ['Reserved.', 'Reserved'],
  0x0004: ['Reserved.', 'Reserved'],
  0x0008: ['Reserved.', 'Reserved'],
  0x0020: ['HIGH_ENTROPY_VA', 'Image can handle a high entropy 64-bit virtual address space.'],
  0x0040: ['DYNAMIC_BASE', 'The DLL can be relocated at load time.'],
  0x0080: ['FORCE_INTEGRITY', 'Code integrity checks are forced. If you set this flag and a section contains only uninitialized data, set the PointerToRawData member of IMAGE_SECTION_HEADER for that section to zero; otherwise, the image will fail to load because the digital signature cannot be verified.'],
  0x0100: ['NX_COMPAT', 'The image is compatible with data execution prevention (DEP).'],
  0x0200: ['NO_ISOLATION', 'The image is isolation aware, but should not be isolated.'],
  0x0400: ['NO_SEH', 'The image does not use structured exception handling (SEH). No handlers can be called in this image.'],
  0x0800: ['NO_BIND', 'Do not bind the image.'],
  0x1000: ['APPCONTAINER', 'Image must execute in an AppContainer'],
  0x2000: ['WDM_DRIVER', 'A WDM driver.'],
  0x4000: ['GUARD_CF', 'Image supports Control Flow Guard'],
  0x8000: ['TERMINAL_SERVER_AWARE', 'The image is terminal server aware.'],
};

const imageDirectory = {
  0: ['EXPORT', 'Export Directory'],
  1: ['IMPORT', 'Import Directory'],
  2: ['RESOURCE', 'Resource Directory'],
  3: ['EXCEPTION', 'Exception Directory'],
  4: ['SECURITY', 'Security Directory'],
  5: ['BASERELOC', 'Base Relocation Directory'],
  6: ['DEBUG', 'Debug Directory'],
  7: ['ARCHITECTURE', 'Architecture specific data'],
  8: ['GLOBALPTR', 'Global pointer register relative virtual address'],
  9: ['TLS', 'Thread local storage directory'],
  10: ['LOAD_CONFIG', 'Load configuration directory'],
  11: ['BOUND_IMPORT', 'Bound import directory'],
  12: ['IAT', 'Import Address Table'],
  13: ['DELAY_IMPORT', 'Delay Import Table'],
  14: ['COM_DESC', 'COM descriptor table'],
  15: ['RESERVED', 'Reserved'],
};

const sectionChrs = {
  0x0001: ['Reserved', 'Reserved'],
  0x0002: ['Reserved', 'Reserved'],
  0x0004: ['Reserved', 'Reserved'],
  0x0008: ['TYPE_NO_PAD', 'The section should not be padded to the next boundary. This flag is obsolete and is replaced by IMAGE_SCN_ALIGN_1BYTES'],
  0x0010: ['Reserved', 'Reserved'],
  0x0020: ['CNT_CODE', 'The section contains executable code'],
  0x0040: ['CNT_INITIALIZED_DATA', 'The section contains initialized data'],
  0x0080: ['CNT_UNINITIALIZED_DATA', 'The section contains uninitialized data'],
  0x0100: ['LNK_OTHER', 'Reserved'],
  0x0200: ['LNK_INFO', 'The section contains comments or other information. This is valid only for object files'],
  0x0400: ['Reserved', 'Reserved'],
  0x0800: ['LNK_REMOVE', 'The section will not become part of the image. This is valid only for object files'],
  0x1000: ['LNK_COMDAT', 'The section contains COMDAT data. This is valid only for object files'],
  0x2000: ['Reserved', 'Reserved'],
  0x4000: ['NO_DEFER_SPEC_EXC', 'Reset speculative exceptions handling bits in the TLB entries for this section'],
  0x8000: ['GPREL', 'The section contains data referenced through the global pointer'],
  0x10000: ['Reserved', 'Reserved'],
  0x20000: ['MEM_PURGEABLE', 'Reserved'],
  0x40000: ['MEM_LOCKED', 'Reserved'],
  0x80000: ['MEM_PRELOAD', 'Reserved'],
  0x100000: ['ALIGN_1BYTES', 'Align data on a 1-byte boundary. This is valid only for object files'],
  0x200000: ['ALIGN_2BYTES', 'Align data on a 2-byte boundary. This is valid only for object files'],
  0x300000: ['ALIGN_4BYTES', 'Align data on a 4-byte boundary. This is valid only for object files'],
  0x400000: ['ALIGN_8BYTES', 'Align data on a 8-byte boundary. This is valid only for object files'],
  0x500000: ['ALIGN_16BYTES', 'Align data on a 16-byte boundary. This is valid only for object files'],
  0x600000: ['ALIGN_32BYTES', 'Align data on a 32-byte boundary. This is valid only for object files'],
  0x700000: ['ALIGN_64BYTES', 'Align data on a 64-byte boundary. This is valid only for object files'],
  0x800000: ['ALIGN_128BYTES', 'Align data on a 128-byte boundary. This is valid only for object files'],
  0x900000: ['ALIGN_256BYTES', 'Align data on a 256-byte boundary. This is valid only for object files'],
  0xA00000: ['ALIGN_512BYTES', 'Align data on a 512-byte boundary. This is valid only for object files'],
  0xB00000: ['ALIGN_1024BYTES', 'Align data on a 1024-byte boundary. This is valid only for object files'],
  0xC00000: ['ALIGN_2048BYTES', 'Align data on a 2048-byte boundary. This is valid only for object files'],
  0xD00000: ['ALIGN_4096BYTES', 'Align data on a 4096-byte boundary. This is valid only for object files'],
  0xE00000: ['ALIGN_8192BYTES', 'Align data on a 8192-byte boundary. This is valid only for object files'],
  0x1000000: ['LNK_NRELOC_OVFL', 'The section contains extended relocations. The count of relocations for the section exceeds the 16 bits that is reserved for it in the section header. If the NumberOfRelocations field in the section header is 0xffff, the actual relocation count is stored in the VirtualAddress field of the first relocation. It is an error if LNK_NRELOC_OVFL is set and there are fewer than 0xffff relocations in the section'],
  0x2000000: ['MEM_DISCARDABLE', 'The section can be discarded as needed'],
  0x4000000: ['MEM_NOT_CACHED', 'The section cannot be cached'],
  0x8000000: ['MEM_NOT_PAGED', 'The section cannot be paged'],
  0x10000000: ['MEM_SHARED', 'The section can be shared in memory'],
  0x20000000: ['MEM_EXECUTE', 'The section can be executed as code'],
  0x40000000: ['MEM_READ', 'The section can be read'],
  0x80000000: ['MEM_WRITE', 'The section can be written to'],
};
